[package]
name = "rust_grep"
version = "0.1.0"
edition = "2021"
authors = ["Mehdi ALAOUI <alaoui.mehdi.1995@gmail.com>"]
description = "Implementation of simpliest version of `grep` command to learn Rust language"

[dependencies]
clap = { version = "3.2.6", features = ["derive"] }
